services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins_container
    restart: always
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/var/jenkins_workspace/erp-be:rw
    environment:
      - JENKINS_OPTS=--httpPort=8080
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  jenkins_data: